name: custom_security_cam
description: "An app to manage a custom designed security camera system"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_storage: ^11.6.6
  firebase_core: ^2.25.4
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^5.0.2
  cloud_firestore: ^4.15.5
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/images/
